# NOTE: Do not edit, file was generated by jhconvert

Name: sugar-artwork
Version: 0.83.3
Release: %mkrel 1
Summary: Artwork for Sugar look-and-feel
License: LGPLv2+
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/glucose/sugar-artwork/sugar-artwork-0.83.3.tar.bz2

Requires: sugar-base >= 0.83.3
Requires: gtk+2  

BuildRequires: icon-slicer  
BuildRequires: icon-naming-utils  
BuildRequires: xcursorgen  
BuildRequires: libgtk+2-devel  

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

%description
Contains the themes and icons that make up the Sugar default look and feel.

%prep
%setup -q -n sugar-artwork-0.83.3


%build
%configure 
make 

%install
rm -rf %{buildroot}
make  \
	DESTDIR=%{buildroot} \
	install


%clean
rm -rf %{buildroot}

%post
%update_icon_cache sugar

%postun
%clean_icon_cache sugar

%files 
%defattr(-,root,root,-)
%_datadir/icons/*
%_datadir/themes/*
%_libdir/gtk*/*/engines/*
%doc COPYING NEWS README

